name: Nightly Release

on:
  schedule:
    - cron: '0 0 * * *' # Runs at midnight every day
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Specify the Python version you need

    - name: Install dependencies
      run: pip install pyinstaller
    - name: Install Heimdall
      run: sudo apt install heimdall-flash -y

    - name: Build executable
      run: pyinstaller --onefile --noconsole --add-binary "/bin/heimdall:." --add-data "$(pwd)/python-logo-only.svg:." gui.py
      working-directory: ${{ github.workspace }}
      
    - name: Update Nightly Release
      uses: andelf/nightly-release@main
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          tag_name: nightly
          name: 'Desktop App Nightly Release $$'
          prerelease: true
          body: 'TODO: Add nightly release notes'
          files: |
            ./dist/gui
